apiVersion: v1
kind: Pod
metadata:
  name: itsmetommy
  labels:
    app: helloworld
spec:
  containers:
  - name: itsmetommy-httpd
    image: httpd
    ports:
    - name: web-port
      containerPort: 80