
apiVersion: v1
kind: Service
metadata:
  name: itsmetommy-service
spec:
  ports:
  - port: 31000
    nodePort: 31000
    targetPort: web-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort